
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Test
tagline:          'Test'
description:      'Test'
url:              aileen365.github.io/hyde
baseurl:          /hyde/

author:
  name:           'Test'
  url:            https://twitter.com/test

github:
  repo:           https://github.com/aileen365/hyde
