# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true


# Setup
title:            Wolfie
tagline:          'Hello Buddy'
description:      'I am the fantastic <a href="http://jekyllrb.com" target="_blank">Wolfie</a> who is incredibly <a href="https://twitter.com/mdo" target="_blank">awesome</a>.'
#url:             aileen365.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aileen365/aileen365.github.io.git
